//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareIdentitySpec) DeepCopyInto(out *HardwareIdentitySpec) {
	*out = *in
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareIdentitySpec.
func (in *HardwareIdentitySpec) DeepCopy() *HardwareIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(HardwareIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestationChallenge) DeepCopyInto(out *NodeAttestationChallenge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestationChallenge.
func (in *NodeAttestationChallenge) DeepCopy() *NodeAttestationChallenge {
	if in == nil {
		return nil
	}
	out := new(NodeAttestationChallenge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeAttestationChallenge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestationChallengeList) DeepCopyInto(out *NodeAttestationChallengeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeAttestationChallenge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestationChallengeList.
func (in *NodeAttestationChallengeList) DeepCopy() *NodeAttestationChallengeList {
	if in == nil {
		return nil
	}
	out := new(NodeAttestationChallengeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeAttestationChallengeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestationChallengeSpec) DeepCopyInto(out *NodeAttestationChallengeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestationChallengeSpec.
func (in *NodeAttestationChallengeSpec) DeepCopy() *NodeAttestationChallengeSpec {
	if in == nil {
		return nil
	}
	out := new(NodeAttestationChallengeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestationChallengeStatus) DeepCopyInto(out *NodeAttestationChallengeStatus) {
	*out = *in
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestationChallengeStatus.
func (in *NodeAttestationChallengeStatus) DeepCopy() *NodeAttestationChallengeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeAttestationChallengeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestationDocument) DeepCopyInto(out *NodeAttestationDocument) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestationDocument.
func (in *NodeAttestationDocument) DeepCopy() *NodeAttestationDocument {
	if in == nil {
		return nil
	}
	out := new(NodeAttestationDocument)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeAttestationDocument) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestationDocumentList) DeepCopyInto(out *NodeAttestationDocumentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeAttestationDocument, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestationDocumentList.
func (in *NodeAttestationDocumentList) DeepCopy() *NodeAttestationDocumentList {
	if in == nil {
		return nil
	}
	out := new(NodeAttestationDocumentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeAttestationDocumentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestationDocumentSpec) DeepCopyInto(out *NodeAttestationDocumentSpec) {
	*out = *in
	in.Measurements.DeepCopyInto(&out.Measurements)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestationDocumentSpec.
func (in *NodeAttestationDocumentSpec) DeepCopy() *NodeAttestationDocumentSpec {
	if in == nil {
		return nil
	}
	out := new(NodeAttestationDocumentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestationDocumentStatus) DeepCopyInto(out *NodeAttestationDocumentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestationDocumentStatus.
func (in *NodeAttestationDocumentStatus) DeepCopy() *NodeAttestationDocumentStatus {
	if in == nil {
		return nil
	}
	out := new(NodeAttestationDocumentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestationPolicy) DeepCopyInto(out *NodeAttestationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestationPolicy.
func (in *NodeAttestationPolicy) DeepCopy() *NodeAttestationPolicy {
	if in == nil {
		return nil
	}
	out := new(NodeAttestationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeAttestationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestationPolicyList) DeepCopyInto(out *NodeAttestationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeAttestationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestationPolicyList.
func (in *NodeAttestationPolicyList) DeepCopy() *NodeAttestationPolicyList {
	if in == nil {
		return nil
	}
	out := new(NodeAttestationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeAttestationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestationPolicySpec) DeepCopyInto(out *NodeAttestationPolicySpec) {
	*out = *in
	if in.TrustedAttestationVerifiers != nil {
		in, out := &in.TrustedAttestationVerifiers, &out.TrustedAttestationVerifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SoftwarePolicy != nil {
		in, out := &in.SoftwarePolicy, &out.SoftwarePolicy
		*out = new(SoftwareAttestationPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestationPolicySpec.
func (in *NodeAttestationPolicySpec) DeepCopy() *NodeAttestationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NodeAttestationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeIdentityEnrollment) DeepCopyInto(out *NodeIdentityEnrollment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeIdentityEnrollment.
func (in *NodeIdentityEnrollment) DeepCopy() *NodeIdentityEnrollment {
	if in == nil {
		return nil
	}
	out := new(NodeIdentityEnrollment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeIdentityEnrollment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeIdentityEnrollmentList) DeepCopyInto(out *NodeIdentityEnrollmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeIdentityEnrollment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeIdentityEnrollmentList.
func (in *NodeIdentityEnrollmentList) DeepCopy() *NodeIdentityEnrollmentList {
	if in == nil {
		return nil
	}
	out := new(NodeIdentityEnrollmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeIdentityEnrollmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeIdentityEnrollmentSpec) DeepCopyInto(out *NodeIdentityEnrollmentSpec) {
	*out = *in
	if in.SoftwareIdentity != nil {
		in, out := &in.SoftwareIdentity, &out.SoftwareIdentity
		*out = new(SoftwareIdentitySpec)
		**out = **in
	}
	if in.HardwareIdentity != nil {
		in, out := &in.HardwareIdentity, &out.HardwareIdentity
		*out = new(HardwareIdentitySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExpectedMeasurements != nil {
		in, out := &in.ExpectedMeasurements, &out.ExpectedMeasurements
		*out = new(NodeMeasurements)
		(*in).DeepCopyInto(*out)
	}
	if in.BootstrapExpiry != nil {
		in, out := &in.BootstrapExpiry, &out.BootstrapExpiry
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeIdentityEnrollmentSpec.
func (in *NodeIdentityEnrollmentSpec) DeepCopy() *NodeIdentityEnrollmentSpec {
	if in == nil {
		return nil
	}
	out := new(NodeIdentityEnrollmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeIdentityEnrollmentStatus) DeepCopyInto(out *NodeIdentityEnrollmentStatus) {
	*out = *in
	if in.LastBootstrapTime != nil {
		in, out := &in.LastBootstrapTime, &out.LastBootstrapTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeIdentityEnrollmentStatus.
func (in *NodeIdentityEnrollmentStatus) DeepCopy() *NodeIdentityEnrollmentStatus {
	if in == nil {
		return nil
	}
	out := new(NodeIdentityEnrollmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeMeasurements) DeepCopyInto(out *NodeMeasurements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeMeasurements.
func (in *NodeMeasurements) DeepCopy() *NodeMeasurements {
	if in == nil {
		return nil
	}
	out := new(NodeMeasurements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SoftwareAttestationPolicy) DeepCopyInto(out *SoftwareAttestationPolicy) {
	*out = *in
	if in.SLSAProvenanceAllowedPrefixes != nil {
		in, out := &in.SLSAProvenanceAllowedPrefixes, &out.SLSAProvenanceAllowedPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SoftwareAttestationPolicy.
func (in *SoftwareAttestationPolicy) DeepCopy() *SoftwareAttestationPolicy {
	if in == nil {
		return nil
	}
	out := new(SoftwareAttestationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SoftwareIdentitySpec) DeepCopyInto(out *SoftwareIdentitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SoftwareIdentitySpec.
func (in *SoftwareIdentitySpec) DeepCopy() *SoftwareIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(SoftwareIdentitySpec)
	in.DeepCopyInto(out)
	return out
}
